name: Production Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

 

jobs:
  build:
    name:  Production Build
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore /p:DebugType=None
    
    - name: Publish
      run: dotnet publish CDCDWebApplication/CDCDWebApplication.csproj -o PublishPractical/CDCDWebApplication/ -r win-x64 --self-contained true /p:DebugType=None
   
    - name: Easy Zip Files
    # You may pin to the exact commit or the version.
    # uses: vimtor/action-zip@5f1c4aa587ea41db1110df6a99981dbe19cee310
      uses: vimtor/action-zip@v1
      with:
        # Files or directories to zip
        files: ./PublishPractical/CDCDWebApplication/
        # Name of output zip file
        dest: ./PublishPractical/cicdpract.zip
        # Whether to add subdirectories to simply zip all files to the root
        #recursive: # optional, default is true
     
    - name: Easy Zip Files
    # You may pin to the exact commit or the version.
    # uses: vimtor/action-zip@5f1c4aa587ea41db1110df6a99981dbe19cee310
      uses: vimtor/action-zip@v1
      with:
        # Files or directories to zip
        files: ./PublishPractical/cicdpract.zip ./PublishPractical/CDCDWebApplication/aws-windows-deployment-manifest.json
        # Name of output zip file
        dest: ./PublishPractical/cicddemo.zip
        # Whether to add subdirectories to simply zip all files to the root
        #recursive: # optional, default is true
     
    - name: Get current time
      uses: srfrnk/current-time@master
      id: current-time
      with:
        format: YYYYMMDDHHmmss   
     
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: cicdpractApp
        environment_name: Cicdpractapp-env
        version_label: cicd-prod-${{ steps.current-time.outputs.formattedTime }}
        region: ap-south-1
        deployment_package: D:/a/CDCDWebApplication/CDCDWebApplication/PublishPractical/cicddemo.zip
        #use_existing_version_if_available: true
     
    - name: MSTeams Notification
      uses: skitionek/notify-microsoft-teams@master
      if: always()
      with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          steps: ${{ toJson(steps) }}
